const table = document.querySelector('.table')
const selectionType = document.getElementById('type')
const selectionIngredient1 = document.getElementById('ingredient_1')
const selectionIngredient2 = document.getElementById('ingredient_2')
const selectionIngredient3 = document.getElementById('ingredient_3')
const buttonAdd = document.querySelector('.button_add')
const ajoutInput = document.querySelector('.ajout input')

buttonAdd.addEventListener('click', ()=>{
    const lign = document.createElement('div')
    const input = document.createElement('div')
    const ingredient1Div = document.createElement('div')
    const ingredient2Div = document.createElement('div')
    const ingredient3Div = document.createElement('div')
    const divButton = document.createElement('div')
    lign.classList.add('lign')
    table.appendChild(lign)
    lign.appendChild(input)
    lign.appendChild(ingredient1Div)
    lign.appendChild(ingredient2Div)
    lign.appendChild(ingredient3Div)
    lign.appendChild(divButton)

})